### PR TITLE
Fix serialization issue with exceptions in RequestHandler

### LINKED ISSUE #1127: Re-throwing the ServletException with previous exception attached leads to empty page
When attempting to attach the previous exception to the newly thrown ServletException (ControllerServlet.php, line 578, branch 1.1) an empty response will be returned if an exception in META-INF is being thrown.

### PR DESCRIPTION
**Pull request by pathmissing**
Adds new utility methods to flatten exceptions before being serialized.

Fixes #1127

### CODE REVIEW

File: src/AppserverIo/Appserver/ServletEngine/RequestHandler.php [hunk 1]
```diff
@@ -186,6 +186,7 @@ public function run()
             }
 
         } catch (\Exception $e) {
+            ErrorUtil::singleton()->flattenExceptionBacktrace($e);
```
Comment (wagnert) [inline src/AppserverIo/Appserver/ServletEngine/RequestHandler.php]: Should be moved from `RequestHandler::run()` to inside `ErrorUtil::fromException()` method as this method can be invoke from somewhere else to.

**Review by wagnert — CHANGES_REQUESTED** [review]
Think we should move the call to `flattenExceptionBacktrace` to the `ErrorUtil::fromException()` method (see comment)

File: src/AppserverIo/Appserver/ServletEngine/RequestHandler.php (hunk 1 above)
Comment (pathmissing) [reply src/AppserverIo/Appserver/ServletEngine/RequestHandler.php]: Updated the pull request.

File: src/AppserverIo/Appserver/ServletEngine/Utils/ErrorUtil.php [hunk 2]
```diff
@@ -51,6 +51,7 @@ class ErrorUtil extends \AppserverIo\Appserver\Core\Utilities\ErrorUtil
      */
     public function fromException(\Exception $e)
     {
+        ErrorUtil::singleton()->flattenExceptionBacktrace($e);
```
Comment (wagnert) [inline src/AppserverIo/Appserver/ServletEngine/Utils/ErrorUtil.php]: Instead of loading the singleton instance with `ErrorUtil::singleton()->flattenExceptionBacktrace($e)` you should use `$this->flattenExceptionBacktrace($e)`.

**Review by wagnert — CHANGES_REQUESTED** [review]

**Review by wagnert — APPROVED** [review]
